# Generated by Django 5.0.4 on 2024-04-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ref_code',
            field=models.CharField(default='knZb0nbt', unique=True),
        ),
    ]
