# Generated by Django 5.0.4 on 2024-04-24 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral_app", "0002_alter_profile_managers_alter_profile_ref_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="ref_code",
            field=models.CharField(default="64DHLjaP", unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="ref_received",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="referrals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
