# Generated by Django 5.0.4 on 2024-04-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_app', '0002_alter_profile_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ref_code',
            field=models.CharField(default='0oPdE6ZY', unique=True),
        ),
    ]
