# Generated by Django 5.0.4 on 2024-04-21 19:35

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_app', '0002_alter_profile_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ref_code',
            field=models.CharField(default='mDYpibZW', unique=True),
        ),
    ]
