# Generated by Django 5.0.4 on 2024-04-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_app', '0003_alter_profile_ref_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AlterField(
            model_name='profile',
            name='ref_code',
            field=models.CharField(default='U7iaMvjE', unique=True),
        ),
    ]
