# Generated by Django 5.0.4 on 2024-04-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_app', '0003_alter_profile_ref_code_alter_profile_ref_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ref_code',
            field=models.CharField(default='E6aYYo', unique=True),
        ),
    ]
