# Generated by Django 5.0.4 on 2024-04-23 18:49

import referral_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_app', '0004_remove_profile_username_alter_profile_ref_code'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('objects', referral_app.models.ProfileManager()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='ref_code',
            field=models.CharField(default='9QiqBUXE', unique=True),
        ),
    ]
