# Generated by Django 5.0.4 on 2024-04-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_app', '0004_alter_profile_options_alter_profile_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ref_code',
            field=models.CharField(default='Z8xVpObf', unique=True),
        ),
    ]
