# Generated by Django 5.0.4 on 2024-04-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_app', '0005_alter_profile_password_alter_profile_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ref_code',
            field=models.CharField(default='XY0VyYOs', unique=True),
        ),
    ]
